export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";
export const AUTH_SET_TOKEN_ONLY = "AUTH_SET_TOKEN_ONLY"
export const AUTH_SET_UID_ONLY = "AUTH_SET_UID_ONLY"

export const SET_IMAGES = "SET_IMAGES";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
